module.exports = {
  arrowParens: 'always',
  singleQuote: true,
  printWidth: 120,
  tabWidth: 2,
  trailingComma: 'es5',
  bracketSameLine: true,
  semi: true,
  importOrder: [
    '^(react/(.*)$)|^(react$)',
    '^(expo-(.*)$)|^(expo$)',
    '<THIRD_PARTY_MODULES>',
    '',
    '^~/constants/(.*)$',
    '^~/fragments/(.*)$',
    '^~/hooks/(.*)$',
    '^~/lib/(.*)$',
    '^~/utils/(.*)$',
    '^~/services/(.*)$',
    '^~/stores/?(.*)$',
    '^~/components/(.*)$',
    '^~/screens/(.*)$',
    '^[./]',
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ['jsx', 'decorators-legacy'],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  plugins: ['@ianvs/prettier-plugin-sort-imports'],
};
